BestCRM/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from crm import urls as crm_urls
from bestadmin import urls as bestadmin_urls
from student import urls as student_urls
from BestCRM import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^crm/', include(crm_urls)),
    url(r'^bestadmin/', include(bestadmin_urls)),
    url(r'^student/', include(student_urls)),

    url(r'^login/', views.acc_login),
    url(r'^logout/', views.acc_logout,name="logout"),
    url(r'^my_courses/', views.my_courses,name="my_courses"),



]

crm/urls.py
from django.conf.urls import include, url
from crm import views

urlpatterns = [
    url(r'^$', views.dashboard),
    url(r'^stu_enrollment/$', views.stu_enrollment,name="stu_enrollment"),
    url(r'^enrollment/(\d+)/$', views.enrollment,name="enrollment"),
    url(r'^enrollment/(\d+)/upload/$', views.enrollment_upload,name="enrollment_upload"),
    url(r'^stu_enrollment/(\d+)/contract_audit/$', views.contract_audit,name="contract_audit"),
]

crm/models.py
from django.db import models

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)

# Create your models here.

class UserInfosManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_superuser = True
        user.save(using=self._db)
        return user



class UserInfos(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,

    )
    name = models.CharField(max_length=64, verbose_name="姓名")
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    #is_admin = models.BooleanField(default=False)
    role = models.ManyToManyField("Role", blank=True, null=True)

    objects = UserInfosManager()   #变量名必须是objects

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email


    class Meta:
        permissions = (
            ('crm_model_detail', '可以查看bestadmin每张表里所有的数据'),
            ('crm_model_change', '可以对bestadmin表里的每条数据进行修改'),
            ('crm_model_add', '可以对bestadmin每张表进行数据添加'),

        )









class Role(models.Model):
    """角色表"""
    name = models.CharField(max_length=32,verbose_name="角色")
    menus = models.ManyToManyField("Menus")

    def __str__(self):
        return self.name



class CustomerInfos(models.Model):
    """客户信息表"""
    name = models.CharField(max_length=32,default=None)
    contact_type_choices = ((0,"qq"),(1,"微信"),(2,"手机"))
    contact_type =models.SmallIntegerField(choices=contact_type_choices,default=0)
    contact = models.CharField(max_length=64,unique=True)
    consult_courses = models.ManyToManyField("Course",verbose_name="咨询课程")
    consult_content = models.TextField(verbose_name="咨询内容")
    consultant = models.ForeignKey("UserInfos",verbose_name="咨询顾问")
    status_choices = ((0,"未报名"),(1,"已报名"),(2,"已退学"))
    status = models.SmallIntegerField(choices=status_choices)
    source_choices = ((0,"QQ群"),(1,"51CTO"),(2,"百度推广"),(3,"知乎"),(4,"转介绍"),(5,"其他"))
    source = models.SmallIntegerField(choices=source_choices)
    referral_from = models.ForeignKey("self",blank=True,null=True)
    id_num = models.CharField(max_length=32,blank=True,null=True)
    sex_choices = ((0,"女"),(1,"男"))
    sex = models.SmallIntegerField(choices=sex_choices,blank=True,null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class CustomerFollowUp(models.Model):
    """客户跟踪记录表"""
    customer = models.ForeignKey("CustomerInfos")
    content = models.TextField(verbose_name="跟进内容")
    user = models.ForeignKey("UserInfos",verbose_name="跟进人")
    status_choices = ((0,"近期无报名计划"),(1,"1个月内报名"),(2,"两周内报名"),(3,"已经报名"))
    status = models.SmallIntegerField(choices=status_choices)
    date = models.DateField(auto_now_add=True)

class Course(models.Model):
    """课程表"""
    name = models.CharField(max_length=32,unique=True,verbose_name="课程名称")
    outline = models.TextField(verbose_name="课程大纲")
    price = models.PositiveSmallIntegerField(verbose_name="课程价格")
    period = models.PositiveSmallIntegerField(verbose_name="课程周期(月)",default=5)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """班级列表"""
    branch = models.ForeignKey("Branch")
    course = models.ForeignKey("Course")
    semester = models.PositiveSmallIntegerField(verbose_name="学期")
    teachers = models.ManyToManyField("UserInfos",verbose_name="讲师")
    contract_template = models.ForeignKey("ContractTemplate",blank=True,null=True)

    start_date = models.DateField(verbose_name="开学时间")
    graduate_date = models.DateField(verbose_name="毕业时间",blank=True,null=True)
    class_type_choices = ((0,"脱产班"),(1,"周末班"),(2,"网络班"))
    class_type = models.SmallIntegerField(choices=class_type_choices,default=0)

    def __str__(self):
        return "%s(%s)期"%(self.course,self.semester)
    class Meta:
        unique_together = ("course","semester","branch","class_type")


class Branch(models.Model):
    """校区表"""
    name = models.CharField(max_length=32,unique=True)
    addr = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class CourseRecord(models.Model):
    """上课记录"""
    class_grade = models.ForeignKey("ClassList",verbose_name="上课班级")
    day_num = models.PositiveSmallIntegerField(verbose_name="课程节次")
    teacher = models.ForeignKey("UserInfos",verbose_name="本节讲师")
    title = models.CharField(verbose_name="本节主题",max_length=32)
    content = models.TextField(verbose_name="本节内容")
    has_homework = models.BooleanField(verbose_name="本节是否有作业",default=True)
    homework = models.TextField(verbose_name="作业需求",null=True,blank=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s(%s)节"%(self.class_grade,self.day_num)
    class Meta:
        unique_together = ("class_grade","day_num")



class StudyRecord(models.Model):
    """学习记录表"""
    course_record = models.ForeignKey('CourseRecord')
    student = models.ForeignKey("Student")

    score_choices = (
        (90,"A"),
        (80,"B"),
        (60,"C"),
        (40,"D"),
        (0,"N/A"),
        (-1,"COPY")
    )
    score = models.SmallIntegerField(choices=score_choices)

    show_choices =(
        (0,"缺勤"),
        (1,"已签到"),
        (2,"迟到"),
        (3,"早退")
    )
    show_status = models.SmallIntegerField(choices=show_choices,default=1)

    note = models.TextField(verbose_name="成绩备注",blank=True,null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s %s"%(self.course_record,self.student,self.score)



class Student(models.Model):
    """学员表"""
    customer = models.OneToOneField("CustomerInfos")
    class_grades = models.ManyToManyField("ClassList")

    def __str__(self):
        return self.customer.name



class Menus(models.Model):
    """菜单表"""
    name = models.CharField(max_length=32)
    url_type_choices = ((0,"absolute"),(1,"dynamic"))
    url_type = models.SmallIntegerField(choices=url_type_choices,default=0)
    url_name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ("name","url_name")


class ContractTemplate(models.Model):
    """合同模板表"""
    name = models.CharField(max_length=32)
    content = models.TextField()
    date = models.DateField(auto_now_add=True)


class StudentEnrollment(models.Model):
    """学员报名表"""
    customer = models.ForeignKey("CustomerInfos")
    class_grade = models.ForeignKey("ClassList")
    consultant = models.ForeignKey("UserInfos")

    contract_argeed = models.BooleanField(default=False)
    contract_argeed_date = models.DateField(verbose_name="客户同意时间",blank=True,null=True)

    contract_approved = models.BooleanField(default=False)
    contract_approved_date = models.DateField(verbose_name="审核通过时间",blank=True, null=True)

    class Meta:
        unique_together = ("customer","class_grade")

    def __str__(self):
        return self.customer.name


class PaymentRecoed(models.Model):
    """学员缴费记录表"""
    enrollment = models.ForeignKey("StudentEnrollment")

    payment_type_choices = ((0,"报名费"),(1,"学费"),(2,"退费"))
    payment_type = models.SmallIntegerField(choices=payment_type_choices,default=0)

    amount = models.IntegerField(verbose_name="费用",default=500)
    consultant = models.ForeignKey("UserInfos")
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return enumerate

crm/forms.py
from django.forms import ModelForm
from crm import models



class CustomerInfo(ModelForm):
    def __new__(cls, *args, **kwargs):  # 重写父类__new__方法
        for field_name in cls.base_fields:  # cls.base_fields 表所有字段类型
            field_obj = cls.base_fields[field_name]  # cls.base_fields 表字段类型对象
            field_obj.widget.attrs.update({"class": "form-control"})

        for field_name in cls.Meta.readonly_fields:
            field_obj = cls.base_fields[field_name]
            field_obj.widget.attrs.update({"disabled":"True"})

        return ModelForm.__new__(cls)

    def clean(self): #定制父类验证方法

        if self.instance.id is not None:
            for field in self.Meta.readonly_fields:
                old_field_val = getattr(self.instance,field)
                new_field_val = self.cleaned_data[field]

                if old_field_val != new_field_val:
                    """添加字段错误"""
                    self.add_error(field,"Readonly Field: this field should be %s ,not %s."%(old_field_val,new_field_val))

    class Meta:
        model = models.CustomerInfos
        fields = "__all__"
        exclude = ["consult_content","consult_courses","status"]
        readonly_fields = ["contact_type","contact","consultant","referral_from","source"]




class AuditForm(ModelForm):
    def __new__(cls, *args, **kwargs):  # 重写父类__new__方法
        for field_name in cls.base_fields:  # cls.base_fields 表所有字段类型
            field_obj = cls.base_fields[field_name]  # cls.base_fields 表字段类型对象
            field_obj.widget.attrs.update({"class": "form-control"})

        for field_name in cls.Meta.readonly_fields:
            field_obj = cls.base_fields[field_name]
            field_obj.widget.attrs.update({"disabled": "True"})

        return ModelForm.__new__(cls)

    def clean(self):  # 定制父类验证方法

        if self.instance.id is not None:
            for field in self.Meta.readonly_fields:
                old_field_val = getattr(self.instance, field)
                new_field_val = self.cleaned_data[field]

                if old_field_val != new_field_val:
                    """添加字段错误"""
                    self.add_error(field,
                                   "Readonly Field: this field should be %s ,not %s." % (old_field_val, new_field_val))

    class Meta:
        model = models.StudentEnrollment
        fields = "__all__"
        exclude = ["contract_approved_date"]
        readonly_fields = ["contract_argeed"]

crm/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.decorators import login_required
from crm import  models
from crm.forms import CustomerInfo,AuditForm
from  django.views.decorators.csrf import csrf_exempt
import os
from django import conf
import json
from django.db.utils import IntegrityError
from django.utils.timezone import datetime


# Create your views here.



@login_required()
def dashboard(request):
    return render(request,"crm/dashboard.html")

@login_required()
def stu_enrollment(request):
    customer_list = models.CustomerInfos.objects.all()
    class_list = models.ClassList.objects.all()

    if request.method == "POST":
        customer_id = request.POST.get("customer_id")
        class_grade_id = request.POST.get("class_grade_id")

        try:
            stu_enrollment_obj = models.StudentEnrollment.objects.create(
                customer_id = customer_id,
                class_grade_id = class_grade_id,
                consultant_id = request.user.userinfos.id

            )

        except IntegrityError as e:
            stu_enrollment_obj = models.StudentEnrollment.objects.get(customer_id=customer_id,class_grade_id = class_grade_id)
            if stu_enrollment_obj.contract_argeed:
                return redirect("/crm/stu_enrollment/%s/contract_audit/"%stu_enrollment_obj.id)

        stu_enrollment_link = "http://localhost:8000/crm/enrollment/%s/"%stu_enrollment_obj.id


    return render(request,"crm/stu_enrollment.html",locals())


def enrollment(request,stu_enrollment_id):
    stu_enrollment_obj = models.StudentEnrollment.objects.get(id=stu_enrollment_id)
    customer_obj = stu_enrollment_obj.customer

    price = stu_enrollment_obj.class_grade.course.price
    form = CustomerInfo(instance=customer_obj)

    if stu_enrollment_obj.contract_argeed:
        return HttpResponse("报名信息正在审核中，请耐心等待......")

    if request.method == "POST":
        form = CustomerInfo(instance=customer_obj,data=request.POST)

        if form.is_valid():
            form.save()
            stu_enrollment_obj.contract_argeed = True
            stu_enrollment_obj.save()

            stu_enrollment_obj.contract_argeed_date = datetime.now()
            stu_enrollment_obj.save()

            return HttpResponse("你已成功提交报名信息，请等待审核......")

        else:
            print("err:",form.errors)


    #列出已经上传的文件

    upload_files = []
    enrollment_upload_dir = os.path.join(conf.settings.CRM_FILE_UPLOAD_DIR, stu_enrollment_id)

    if os.path.isdir(enrollment_upload_dir):  # 判断文件夹存不存在

        upload_files = os.listdir(enrollment_upload_dir)



    return render(request,"crm/enrollment.html",locals())



@csrf_exempt
def enrollment_upload(request,enrollment_id):
    print(request.FILES)

    enrollment_upload_dir = os.path.join(conf.settings.CRM_FILE_UPLOAD_DIR,enrollment_id)  #保存上传文件的文件夹路径


    if not os.path.isdir(enrollment_upload_dir):  #判断文件夹存不存在

        os.mkdir(enrollment_upload_dir)


    file_obj = request.FILES.get("file")


    if len(os.listdir(enrollment_upload_dir)) <= 2:
        file_path = os.path.join(enrollment_upload_dir, file_obj.name)
        f = open(file_path, "wb")
        for chunk in file_obj.chunks():
            f.write(chunk)
        f.close()

    else:
        return HttpResponse(json.dumps({"status":False,"err_msg":"最多可上传两个文件!"}))


    return HttpResponse(json.dumps({"status":True}))



def contract_audit(request,stu_enrollment_id):

    stu_enrollment_obj = models.StudentEnrollment.objects.get(id=stu_enrollment_id)
    enrollment_form = CustomerInfo(instance=stu_enrollment_obj.customer)
    audit_form = AuditForm(instance=stu_enrollment_obj)

    if request.method == "POST":
        audit_form = AuditForm(instance=stu_enrollment_obj,data=request.POST)
        if audit_form.is_valid():
            audit_form.save()
            stu_enrollment_obj.contract_approved_date = datetime.now()
            stu_enrollment_obj.save()

            stu_obj = models.Student.objects.get_or_create(customer=stu_enrollment_obj.customer)[0]  #这是一个元组
            stu_obj.class_grades.add(stu_enrollment_obj.class_grade_id)
            stu_obj.save()

            stu_enrollment_obj.customer.status = 1
            stu_enrollment_obj.customer.save()


            return redirect("/bestadmin/crm/customerinfos/%s/change/"%stu_enrollment_obj.customer.id)

    return render(request,"crm/contract_audit.html",locals())

templates/crm/contract_audit.html
{% extends "index.html" %}

{% block content %}
    <h2 class="page-header">学员报名|信息审核</h2>

    <div>
    <form class="form" method="post" >
          {% csrf_token %}
            {% for field in enrollment_form %}
                <div class="form-group col-lg-6">
                    <label  class="control-label col-lg-2">{{ field.label }}</label>
                    <div class="col-lg-10">
                        {{ field }}<span style="color: red">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
    </form>
    </div>

    <hr>

    <div>
    <form class="form" method="post" onsubmit="return BeforeSummitDisabledFalse(this)">
          {% csrf_token %}
            {% for field in audit_form %}
                <div class="form-group col-lg-6">
                    <label  class="control-label col-lg-2">{{ field.label }}</label>
                    <div class="col-lg-10">
                        {{ field }}<span style="color: red">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
        <input type="submit" class="pull-right btn btn-success" value="审核通过">
    </form>
    </div>





{% endblock %}

{% block js %}
<script>

function BeforeSummitDisabledFalse(ele) {
    $("#id_contract_argeed").removeAttr("disabled")

    if (!$("#id_contract_approved").prop("checked")){
        alert("请先勾选Contract approved！")
        return false
    }
}




</script>




{% endblock %}

templates/crm/dashboard.html
{% extends "index.html" %}

templates/crm/enrollment.html
{% extends "index.html" %}

{% block css %}
    <link href="/static/plugins/dropzone/dropzone.css" rel="stylesheet" type="text/css">

{% endblock %}

{% block body %}
    <div class="container">
    <h3>华广IT培训|学员登记信息</h3>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">学员信息填写</h3>
      </div>
      <div class="panel-body">
          <form class="form" method="post" onsubmit="return BeforeSummitDisabledFalse(this)">
          {% csrf_token %}
            {% for field in form %}
                <div class="form-group col-lg-6">
                    <label  class="control-label col-lg-2">{{ field.label }}</label>
                    <div class="col-lg-10">
                        {{ field }}<span style="color: red">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}

                <div class="form-group col-lg-6">
                    <label  class="control-label col-lg-2">学费</label>
                    <div class="col-lg-10">
                        {{ price }}
                    </div>
                </div>

                <div class="form-group col-lg-6">
                    <label  class="control-label col-lg-2">所报班级</label>
                    <div class="col-lg-10">
                        {{ stu_enrollment_obj.class_grade }}
                    </div>
                </div>



                <hr>
                <pre style="height: 400px">{{ stu_enrollment_obj.class_grade.contract_template.content }}</pre>
                <p><input type="checkbox" name="contract_agreed" id="contract_agreed">已阅读合同内容，同意合同内一切协议。</p>
                <input type="submit" class="btn btn-info" value="提交">
          </form>

            <label>已经上传的文件：</label>
            <ul id="uploaded_files">
                {% for file in upload_files %}
                    <li>{{ file }}</li>
                {% endfor %}
            </ul>

            <form id="myDropZone"  class="dropzone" action="{% url "enrollment_upload" stu_enrollment_id %}">
              <div class="fallback">
                <input name="file" type="file" multiple />
              </div>
            </form>


      </div>


    </div>


    </div>



{% endblock %}

{% block js %}

    <script src="/static/plugins/dropzone/dropzone.js"></script>




    <script>

        function BeforeSummitDisabledFalse(ele) {
            var select_eles =document.getElementsByTagName("select")
            for (var i=0;i<select_eles.length;i++){
                select_eles[i].removeAttribute("disabled")
            }

            var input_eles =document.getElementsByTagName("input")
            for (var i=0;i<input_eles.length;i++){
                input_eles[i].removeAttribute("disabled")
            }

            if ($("#uploaded_files").children().length == 0){
                alert("请上传相关证件文件！")
                return false
            }

            if (!$("#contract_agreed").prop("checked")){
                alert("必须勾选同意合同才能提交！")
                return false
            }

        }


        Dropzone.options.myDropZone = {
          paramName: "file", // The name that will be used to transfer the file
          maxFilesize: 2, // 最大上传文件MB
          maxFiles:2,     //一次性最多上传两个
          parallelUploads:1,
          accept: function(file, done) {
            if (file.name == "justinbieber.jpg") {
              done("Naha, you don't.");
            }
            else { done(); }
          }
        };


        Dropzone.autoDiscover = false;    //您必须在$（document）.ready之前放置autoDiscover选项
        $(function() {
          // Now that the DOM is fully loaded, create the dropzone, and setup the
          // event listeners
          // Prevent Dropzone from auto discovering this element:

          Dropzone.options.myDropZone = false;    //避免重新创建
          var myDropzone = new Dropzone("#myDropZone");

          myDropzone.on("success", function(file,response) {
            /* Maybe display some more file information on your page */
             console.log("completet", file, response);
             var response = JSON.parse(response);
             if (!response.status){
                 alert(response.err_msg);
             }else {
                 $("#uploaded_files").append("<li>"+ file.name +"</li>");

             }

          });
        })



    </script>








{% endblock %}

templates/crm/stu_enrollment.html
{% extends "index.html" %}

{% block content %}
    <h2 class="page-header">学员报名页</h2>

    <form class="form-horizontal" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="customer" class="col-sm-2 control-label">客户</label>
        <div class="col-sm-10">
            <select name="customer_id" class="form-control" id="customer">
                {% for customer in customer_list %}
                    <option value="{{ customer.id }}">{{ customer }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="class_grade" class="col-sm-2 control-label">报名班级</label>
        <div class="col-sm-10">
            <select name="class_grade_id" class="form-control" id="class_grade">
                {% for class_grade in class_list %}
                    <option value="{{ class_grade.id }}">{{ class_grade }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <input type="submit" class="pull-right btn btn-success" value="下一步">


    </form>




    {% if stu_enrollment_link %}
        <p>请复制此链接发送给学员填写报名信息>>{{ stu_enrollment_link }}</p>
    {% endif %}

{% endblock %}